### ISSUE TITLE
Update to 2022.12.3 :: Buttons are now yellow when active

### ISSUE THREAD

**Issue by BunpGhost** [JuanMTech/ios_light_mode_theme#5]
Hi,

so, after de update, all my buttons show up as yellow, instead of blue :(

The same for the dark theme.

**Comment by JuanMTech** [comment]
Should be fixed now.

**Comment by BunpGhost** [comment]
I have updated and it is still the same.
The color is yellow instead of blue
![image](https://user-images.githubusercontent.com/25492163/212309665-b722abf9-891b-41dc-bbb1-3323f4703d46.png)

@JuanMTech Am I doing something wrong?

Can you please re-open the issue?
